// Small React shim for lucide-react icons addressed by string name.
//
// Section E content (`content.tsx`, ported from
// `claude-design-project/jsx/data.jsx`) carries icon names as strings such as
// `"GitMerge"` or `"MessageSquare"`. The original prototype rendered these
// via `lucide.createIcons()` against a global; in our React/TS codebase we
// resolve a string → component map at render time and let lucide-react own
// the SVG output.
//
// To add a new icon: import it from "lucide-react" and add it to ICONS.
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  BarChart3,
  Beaker,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Calendar,
  CalendarCheck,
  CheckCircle,
  ChevronsRight,
  ChevronsRightLeft,
  Clock,
  Compass,
  Cpu,
  Database,
  Droplets,
  Eye,
  FileSpreadsheet,
  FileText,
  Film,
  Folder,
  FolderLock,
  FolderOpen,
  GitBranch,
  GitMerge,
  Globe,
  Hammer,
  History,
  Inbox,
  Info,
  LayoutGrid,
  Layers,
  Library,
  Link,
  ListTree,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Network,
  NotebookPen,
  Package,
  Plug,
  Puzzle,
  Repeat,
  Reply,
  Route,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  Sparkles,
  Square,
  Sun,
  Target,
  Telescope,
  Terminal,
  Ticket,
  Triangle,
  Trash2,
  TrendingDown,
  Upload,
  Usb,
  Users,
  Wand2,
  Workflow,
  Wrench,
  Youtube,
  Zap,
  type LucideIcon as LucideIconType,
} from "lucide-react";

const ICONS: Record<string, LucideIconType> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  BarChart3,
  Beaker,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Calendar,
  CalendarCheck,
  CheckCircle,
  ChevronsRight,
  ChevronsRightLeft,
  Clock,
  Compass,
  Cpu,
  Database,
  Droplets,
  Eye,
  FileSpreadsheet,
  FileText,
  Film,
  Folder,
  FolderLock,
  FolderOpen,
  GitBranch,
  GitMerge,
  Globe,
  Hammer,
  History,
  Inbox,
  Info,
  LayoutGrid,
  Layers,
  Library,
  Link,
  ListTree,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Network,
  NotebookPen,
  Package,
  Plug,
  Puzzle,
  Repeat,
  Reply,
  Route,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  Sparkles,
  Square,
  Sun,
  Target,
  Telescope,
  Terminal,
  Ticket,
  Triangle,
  Trash2,
  TrendingDown,
  Upload,
  Usb,
  Users,
  Wand2,
  Workflow,
  Wrench,
  Youtube,
  Zap,
};

export interface LucideIconProps {
  name: string;
  size?: number;
  color?: string;
  className?: string;
  strokeWidth?: number;
}

export function LucideIcon({
  name,
  size = 18,
  color,
  className,
  strokeWidth,
}: LucideIconProps) {
  const Comp = ICONS[name];
  if (!Comp) return null;
  return (
    <Comp
      size={size}
      color={color}
      className={className}
      strokeWidth={strokeWidth}
    />
  );
}
