import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 920 }, reducedMotion: "reduce" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173/?dev=proto19b", { waitUntil: "networkidle" });
await page.waitForTimeout(400);
await page.locator('[data-testid="slide"]').screenshot({ path: "/tmp/p19b/rm-step0.png" });
const smil = await page.$$eval("animateMotion", (els) => els.length);
console.log("SMIL nodes at step0 (reduced):", smil);
await page.keyboard.press("Space");
await page.waitForTimeout(300);
console.log("SMIL nodes at step1 (reduced):", await page.$$eval("animateMotion", (els) => els.length));
await page.keyboard.press("Space");
await page.waitForTimeout(300);
await page.locator('[data-testid="slide"]').screenshot({ path: "/tmp/p19b/rm-step2.png" });
console.log("SMIL nodes at step2 (reduced):", await page.$$eval("animateMotion", (els) => els.length));
console.log("pageerrors:", errors.length ? errors : "none");
await browser.close();
